public class Dog extends Memmal {
    
    public void bark(){
        System.debug('Dogs bark... ');
    }
    Override
    public void eat(){
        System.debug('Dogs eat...');
    }
    Override
      public virtual void drink(){
        System.debug('Dogs drink...');
    }

     Override
	 public void feedWithMilk(){
        System.debug('Dogs feed their babies with milk...');
            
    }
}